### ISSUE TITLE
Compuertas lógicas 

### ISSUE THREAD

**Issue by Paola939** [SistemasTecTlaxiaco/compuertas-logicas-equipo-isaias-paola-ariadna-arisbeth#1]
[Simplificacion de circuito.pdf](https://github.com/SistemasTecTlaxiaco/compuertas-logicas-equipo-isaias-paola-ariadna-arisbeth/files/13608405/Simplificacion.de.circuito.pdf)

https://github.com/SistemasTecTlaxiaco/compuertas-logicas-equipo-isaias-paola-ariadna-arisbeth/assets/143351780/d30a1889-ec69-4c64-ac59-18cb84e17027

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
